"""Prompt templates for the research gap agent."""

from research_gap_agent.prompts.templates import (
    DEEP_ANALYSIS_PROMPT,
    GAP_FINDER_PROMPT,
    HYPOTHESIS_GENERATION_PROMPT,
    QUERY_DECOMPOSITION_PROMPT,
    RELEVANCE_SCORING_PROMPT,
    REPORT_WRITING_PROMPT,
    TOPIC_CLUSTERING_PROMPT,
)

__all__ = [
    "DEEP_ANALYSIS_PROMPT",
    "GAP_FINDER_PROMPT",
    "HYPOTHESIS_GENERATION_PROMPT",
    "QUERY_DECOMPOSITION_PROMPT",
    "RELEVANCE_SCORING_PROMPT",
    "REPORT_WRITING_PROMPT",
    "TOPIC_CLUSTERING_PROMPT",
]
